In [1]:
import numpy as np

In [2]:
# dado a pontuação de um jogo de basquete:
joao_pts = [20,30,50,15]
pedro_pts = [100,24,48,23]
maria_pts = [92,22,34,12]
marcos_pts = [12,34,12,43]

In [3]:
# construit o array pontos com todos os resultados:
pontos = np.array([joao_pts,pedro_pts,maria_pts,marcos_pts])

In [4]:
pontos

array([[ 20,  30,  50,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [5]:
# Quem fez mais pontos
pontos.max()

100

In [6]:
# quem fez menos pontos
pontos.min()

12

In [8]:
# qual foi a media de pontos
np.round(pontos.mean())

36.0

In [9]:
# extrair da tabela os pontos de maria
pontos_maria = pontos[2,:]

In [10]:
pontos_maria

array([92, 22, 34, 12])

In [12]:
# qual foi a media de pontos de maria
round(pontos_maria.mean())

40.0

In [13]:
# extrair da tabela os pontos de marcos
pontos_marcos = pontos[3,:]

In [14]:
pontos_marcos

array([12, 34, 12, 43])

In [15]:
# Retornar coeficientes de correlação produto-momento.
np.corrcoef(pontos)

array([[ 1.        , -0.08433623, -0.13228671, -0.54574584],
       [-0.08433623,  1.        ,  0.98986439, -0.78865755],
       [-0.13228671,  0.98986439,  1.        , -0.747667  ],
       [-0.54574584, -0.78865755, -0.747667  ,  1.        ]])

In [17]:
# correlação cruzada entre marcos e maria
np.correlate(pontos_marcos,pontos_maria,'same')

array([ 816, 1564, 2776, 4854])

In [18]:
# Quantil de q'th `dos dados ao longo do eixo especificado em 50% 
np.quantile(pontos,0.5)

27.0

In [19]:
# formato da matriz e de 4 linhas e 4 colunas
np.shape(pontos)

(4, 4)

In [20]:
# matriz de 2 dimensoes
np.ndim(pontos)

2

In [21]:
my_data = np.arange(0,20)

In [22]:
my_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
mydata_m = my_data.reshape(5,4)

In [25]:
mydata_m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
mydata_m[2,2]

10

In [27]:
# localizar o elemnto 15
mydata_m.item(15)

15

In [28]:
m1 = ['python','e','legal']
m2 = ['Guido','Van','Rossum']
m3 = [10,20,30]

In [29]:
lista_m = [m1,m2,m3]

In [30]:
lista_m

[['python', 'e', 'legal'], ['Guido', 'Van', 'Rossum'], [10, 20, 30]]

In [31]:
np.array([m1,m2,m3])

array([['python', 'e', 'legal'],
       ['Guido', 'Van', 'Rossum'],
       ['10', '20', '30']], dtype='<U6')

## MODELO DE LOGICA DO PROJETO DUELLO

In [78]:
m1 = {'nome':'Janderson','idade':38,'faixa':'laranja'}
m2 = {'nome':'Jose','idade':23,'faixa':'azul'}
m3 = {'nome':'Maria','idade':48,'faixa':'vermelha'}
m4 = {'nome':'Inacia','idade':12,'faixa':'branca'}
m5 = {'nome':'Marcos','idade':18,'faixa':'branca'}
m6 = {'nome':'Pedro','idade':7,'faixa':'azul'}
m7 = {'nome':'Marina','idade':38,'faixa':'laranja'}
m8 = {'nome':'Marcelo','idade':38,'faixa':'preta'}

In [79]:
dados = np.array([m1,m2,m3,m4,m5,m6,m7,m8])

In [80]:
dados[0]

{'nome': 'Janderson', 'idade': 38, 'faixa': 'laranja'}

In [81]:
dados[0]['idade']

38

In [82]:
dados[0]['idade'] == 30

False

In [83]:
dados[0]['idade'] == 38

True

In [84]:
dados

array([{'nome': 'Janderson', 'idade': 38, 'faixa': 'laranja'},
       {'nome': 'Jose', 'idade': 23, 'faixa': 'azul'},
       {'nome': 'Maria', 'idade': 48, 'faixa': 'vermelha'},
       {'nome': 'Inacia', 'idade': 12, 'faixa': 'branca'},
       {'nome': 'Marcos', 'idade': 18, 'faixa': 'branca'},
       {'nome': 'Pedro', 'idade': 7, 'faixa': 'azul'},
       {'nome': 'Marina', 'idade': 38, 'faixa': 'laranja'},
       {'nome': 'Marcelo', 'idade': 38, 'faixa': 'preta'}], dtype=object)

In [87]:
if dados[6]['idade'] == dados[7]['idade'] and dados[6]['faixa'] == dados[7]['faixa']:
    print('luta principal' + dados[6]['nome'] + ' contra ' + dados[7]['nome'])
if dados[6]['idade'] == dados[7]['idade'] or dados[6]['faixa'] == dados[7]['faixa']:
    print('luta secundaria: ' + dados[6]['nome'] + ' contra ' + dados[7]['nome'])
else:
    print('Não satisfaz os requerimentos')

luta secundaria: Marina contra Marcelo
