In [1]:
import numpy as np

In [3]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])

In [4]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
print( np.shape(m1))
print( np.ndim(m1))
print( np.shape(m2))
print(np.ndim(m2))

(2, 3)
2
(2, 3)
2


In [11]:
m2 / m1

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [12]:
m2 // m1

array([[7, 4, 3],
       [2, 2, 2]], dtype=int32)

In [13]:
m2 % m1

array([[0, 0, 0],
       [2, 1, 0]], dtype=int32)

In [14]:
np.round(m2 / m1)

array([[7., 4., 3.],
       [2., 2., 2.]])

In [15]:
np.sum(m1)

21

In [17]:
m1_p = np.round((m1 / 21) * 100,0)

In [18]:
m1_p

array([[ 5., 10., 14.],
       [19., 24., 29.]])

In [19]:
np.sum(m1_p)

101.0