In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30])

In [3]:
a

array([10, 20, 30])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.shape(a)

(3,)

In [6]:
mat = np.array([[1,2],[3,4]])

In [7]:
mat

array([[1, 2],
       [3, 4]])

In [8]:
np.shape(mat)

(2, 2)

In [9]:
mat[1][1] # segundo elemento da linha(1) e segundo elemnto da coluna(1)

4

In [11]:
mat[1,1] # outra forma de indexar

4

In [12]:
mat[0,1] # primeiro elemnto da segunda coluna(1) e na primeira linha(0)

2

In [13]:
mat[1,1]

4

In [14]:
mat[-1,-1]

4

In [16]:
mat[:,1] # exibe a segunda coluna

array([2, 4])

In [17]:
mat[1,:] # exibe a segunda linha

array([3, 4])

In [18]:
mat.transpose() # obter a matriz transposta: coluna vira linha e linha vira coluna

array([[1, 3],
       [2, 4]])

In [19]:
matx = np.round(np.random.randn(100)*100,0).reshape(20,5)

In [20]:
matx

array([[  11.,  116.,  -41.,  -41.,  127.],
       [  18.,   91.,  106.,  -64.,   45.],
       [-247.,   -4.,   36.,   94.,  -53.],
       [ 146.,  105.,  167.,   -7.,  152.],
       [ 134.,   61.,  -35.,  -57.,  342.],
       [  44.,  -41.,   10.,  -18.,  125.],
       [ 143.,  -58.,  -93.,  -99.,   32.],
       [ -15.,  106.,   -9.,  101.,   40.],
       [ 103.,  -73.,  202.,  -38., -182.],
       [ -37.,  -12.,  -33., -252.,   54.],
       [ -99.,  105.,  -39., -148.,   50.],
       [ 187.,  155.,   31.,  -79.,   28.],
       [  33.,  -95.,   45., -163.,   25.],
       [  -9.,  -59.,  -61., -101., -231.],
       [ -15.,  -42., -243.,   -1.,  -32.],
       [ -46.,  -85., -134.,  205.,  -86.],
       [  47., -100.,  -60.,   10.,  -39.],
       [-102.,  165.,    1.,  -56.,  181.],
       [ -33., -190.,   -7.,   51.,   21.],
       [  19.,   66.,   42.,  137.,   17.]])

In [21]:
matx.min()

-252.0

In [22]:
matx.max()

342.0

In [23]:
np.sum(matx)

468.0

In [34]:
matxp = np.round((matx / 468) * 100,0)

In [35]:
matxp

array([[  2.,  25.,  -9.,  -9.,  27.],
       [  4.,  19.,  23., -14.,  10.],
       [-53.,  -1.,   8.,  20., -11.],
       [ 31.,  22.,  36.,  -1.,  32.],
       [ 29.,  13.,  -7., -12.,  73.],
       [  9.,  -9.,   2.,  -4.,  27.],
       [ 31., -12., -20., -21.,   7.],
       [ -3.,  23.,  -2.,  22.,   9.],
       [ 22., -16.,  43.,  -8., -39.],
       [ -8.,  -3.,  -7., -54.,  12.],
       [-21.,  22.,  -8., -32.,  11.],
       [ 40.,  33.,   7., -17.,   6.],
       [  7., -20.,  10., -35.,   5.],
       [ -2., -13., -13., -22., -49.],
       [ -3.,  -9., -52.,  -0.,  -7.],
       [-10., -18., -29.,  44., -18.],
       [ 10., -21., -13.,   2.,  -8.],
       [-22.,  35.,   0., -12.,  39.],
       [ -7., -41.,  -1.,  11.,   4.],
       [  4.,  14.,   9.,  29.,   4.]])

In [36]:
np.sum(matxp)

101.0

In [37]:
np.transpose(matxp)

array([[  2.,   4., -53.,  31.,  29.,   9.,  31.,  -3.,  22.,  -8., -21.,
         40.,   7.,  -2.,  -3., -10.,  10., -22.,  -7.,   4.],
       [ 25.,  19.,  -1.,  22.,  13.,  -9., -12.,  23., -16.,  -3.,  22.,
         33., -20., -13.,  -9., -18., -21.,  35., -41.,  14.],
       [ -9.,  23.,   8.,  36.,  -7.,   2., -20.,  -2.,  43.,  -7.,  -8.,
          7.,  10., -13., -52., -29., -13.,   0.,  -1.,   9.],
       [ -9., -14.,  20.,  -1., -12.,  -4., -21.,  22.,  -8., -54., -32.,
        -17., -35., -22.,  -0.,  44.,   2., -12.,  11.,  29.],
       [ 27.,  10., -11.,  32.,  73.,  27.,   7.,   9., -39.,  12.,  11.,
          6.,   5., -49.,  -7., -18.,  -8.,  39.,   4.,   4.]])

In [38]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

In [39]:
m1

array([[1, 2],
       [3, 4]])

In [40]:
m2

array([[5, 6],
       [7, 8]])

In [41]:
m1 + m2 # soma de duas matrizes 1+5 , 2+6 , 3+7 , 4+8 

array([[ 6,  8],
       [10, 12]])

In [42]:
m1 - m2

array([[-4, -4],
       [-4, -4]])

In [43]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [44]:
m1 / m2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [45]:
m1 ** m2

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

In [46]:
m3 = np.array([1,6,9,2,0,10,7,5])

In [47]:
m3.sum()

40

In [48]:
m3.min()

0

In [49]:
m3.max()

10

In [50]:
m3.argmin()

4

In [51]:
m3.argmax()

5

In [52]:
m3.mean()

5.0

In [54]:
m4 = np.array([[9,10],[11,12]])

In [55]:
m1 + m2 + m4

array([[15, 18],
       [21, 24]])

In [57]:
sum(m4)

array([20, 22])

In [58]:
np.diagonal(matxp) # extrai a linha diagonal da matriz 

array([ 2., 19.,  8., -1., 73.])

In [60]:
np.ndim(matxp) # dimensoa da matriz

2

In [61]:
mat2 = np.array([[[1,2,3,4],[5,6,7,8]]])

In [62]:
mat2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [63]:
np.ndim(mat2) # matriz de 3 dimensoes

3