In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
np.insert(arr,1,10) # o metodo insert insere o elemento 10 na posição 1 do array arr

array([ 1, 10,  2,  3])

In [5]:
arr

array([1, 2, 3])

In [6]:
np.insert(arr,2,50)

array([ 1,  2, 50,  3])

In [7]:
a = np.array([[1,2],[3,4]])

In [8]:
a

array([[1, 2],
       [3, 4]])

In [9]:
a.ndim

2

In [10]:
a.sum(axis=0)

array([4, 6])

In [11]:
a.sum(axis=1)

array([3, 7])

In [12]:
m1 = np.array([[10,20,30,50,10],[60,30,20,80,10]])

In [13]:
m1

array([[10, 20, 30, 50, 10],
       [60, 30, 20, 80, 10]])

In [15]:
m1.sum() # a soma de todas as lihas e colunas

320

In [16]:
m1.sum(axis=0) # a soma das colunas

array([ 70,  50,  50, 130,  20])

In [17]:
m1.sum(axis=1) # a soma de todas as linhas

array([120, 200])

In [18]:
a

array([[1, 2],
       [3, 4]])

In [19]:
np.insert(a, 1, 5, axis=1) # insere o numero 5 na coluna 1 

array([[1, 5, 2],
       [3, 5, 4]])

In [20]:
np.insert(a, 1, 7, axis=0) # insere o numero 7 na linha 1

array([[1, 2],
       [7, 7],
       [3, 4]])

In [21]:
# metodo append , anexar valores

In [22]:
a = np.array([1,2,3])

In [23]:
a

array([1, 2, 3])

In [24]:
np.append(a,[4,5,6])

array([1, 2, 3, 4, 5, 6])

In [25]:
a

array([1, 2, 3])

In [26]:
a = np.array([[1,2],[3,4]])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [29]:
np.append(a,[[5,6]])

array([1, 2, 3, 4, 5, 6])

In [30]:
np.append(a,[[7,8]], axis=0) # deve ter o mesmo numero de dimensoes

array([[1, 2],
       [3, 4],
       [7, 8]])

In [35]:
a.ndim

2

In [36]:
a

array([[1, 2],
       [3, 4]])

In [42]:
a = np.array([[1,2],[3,4],[5,6]])

In [43]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.delete(a, 1, 0) # metodo delete (array, posição, eixo=0 ou 1)

array([[1, 2],
       [5, 6]])

In [45]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np.delete(a,1,1) # eixo 1 deletou a coluna

array([[1],
       [3],
       [5]])

In [48]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [49]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
np.delete(a, np.s_[::2],0) # metodo delete com intervalo de 2 linhas, eixo 0

array([[ 4,  5,  6],
       [10, 11, 12]])

In [51]:
np.delete(a, np.s_[::2],1) # metodo delete com intervalo de 2 colunas, eixo 1

array([[ 2],
       [ 5],
       [ 8],
       [11]])