In [2]:
import numpy as np

In [3]:
arr = np.arange(0,16) # definindo um array de 16 elementos ( 0 a 15)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
arr + arr # operação de adição de dois arrays, os arrays precisam ser do mesmo tamanho

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039], dtype=int32)

In [10]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
sum(arr)

120

In [14]:
arrp = np.round((arr / 120) * 100)

In [15]:
sum(arrp)

100.0

In [16]:
np.sqrt(arr) # metodo sqrt para extrair raiz quadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [17]:
np.exp(arr) # metodo exp para aplicar exponenciação

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [18]:
np.mean(arr) # metodo mean para extrair as media de todos os elementos

7.5

In [19]:
np.std(arr) # metodo std para extrair o desvio padrao do array

4.6097722286464435

In [20]:
np.sin(arr) # metodo sin para extrair o seno de todos os elementos

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [21]:
np.max(arr) # metodo max para extrair o valor maximo do array

15

In [22]:
np.min(arr) # metodo min para extrair o valor minimo

0

### Outras formas de extrair o valor maximo, minimo e a media :

In [24]:
arr.max()

15

In [25]:
arr.min()

0

In [27]:
arr.mean()

7.5

In [28]:
arr.std()

4.6097722286464435

In [29]:
arr.argmin()

0

In [30]:
arr.argmax()

15

### Funções estatisticas:

In [5]:
arr = np.random.randn(20).reshape(5,4) # matriz com numeros randomicos de 5 linhas e 4 colunas

In [6]:
arr

array([[-1.33218407, -0.14747529, -0.75239626, -0.32468267],
       [ 2.54807613,  0.83777292, -1.34330607, -0.04318903],
       [ 0.10164775, -1.26918614,  0.10758845, -2.47296735],
       [-0.25808464,  1.06061625,  2.57435415, -0.04404538],
       [-0.33415656,  1.09350459, -0.46184233,  0.49074098]])

In [7]:
arr.max()

2.5743541507829657

In [8]:
arr.argmax()

14

In [9]:
arr.min()

-2.472967347550636

In [10]:
arr.argmin()

11

In [11]:
arr.mean()

0.0015392703282027132

In [14]:
np.amin(arr) # Retorne o mínimo de uma matriz ou mínimo ao longo do eixo

-2.472967347550636

In [15]:
np.amax(arr) # Retorne o máximo de uma matriz ou máximo ao longo de um eixo.

2.5743541507829657

In [16]:
np.nanmin(arr) # Retorno mínimo de uma matriz ou mínimo ao longo do eixo, ignorando qualquer NaNs.

-2.472967347550636

In [17]:
np.nanmax(arr) # Retorne o máximo de uma matriz ou máximo ao longo do eixo, ignorando qualquer NaNs.

2.5743541507829657

In [18]:
np.ptp(arr) # Intervalo de valores (máximo - mínimo) ao longo do eixo.

5.047321498333602

In [20]:
np.percentile(arr,50) # Calcule o percentil qth dos dados ao longo do eixo especificado. 50%

-0.09576033626021604

In [21]:
np.percentile(arr,100) # Calcule o percentil qth dos dados ao longo do eixo especificado. 100%

2.5743541507829657

In [22]:
np.nanpercentile(arr,75) # Calcule o percentil qth dos dados ao longo do eixo especificado. 75% ignorando NaNs

0.5774989604989332

In [24]:
np.quantile(arr,0.5) # Calcular o Quantil de q'th `dos dados ao longo do eixo especificado.

-0.09576033626021604

In [26]:
np.quantile(arr,0.75)

0.5774989604989332

In [27]:
np.average(arr) # Calcule a média ponderada ao longo do eixo especificado

0.0015392703282027132

In [28]:
np.var(arr) # Calcule a variância ao longo do eixo especificado.

1.439971355201567

In [29]:
np.corrcoef(arr) # Retorne coeficientes de correlação produto-momento.

array([[ 1.        , -0.47055041, -0.7557039 ,  0.19265219,  0.84329116],
       [-0.47055041,  1.        ,  0.15182309, -0.76992582,  0.07527429],
       [-0.7557039 ,  0.15182309,  1.        ,  0.40510116, -0.72948937],
       [ 0.19265219, -0.76992582,  0.40510116,  1.        , -0.21828629],
       [ 0.84329116,  0.07527429, -0.72948937, -0.21828629,  1.        ]])

In [32]:
arr

array([[-1.33218407, -0.14747529, -0.75239626, -0.32468267],
       [ 2.54807613,  0.83777292, -1.34330607, -0.04318903],
       [ 0.10164775, -1.26918614,  0.10758845, -2.47296735],
       [-0.25808464,  1.06061625,  2.57435415, -0.04404538],
       [-0.33415656,  1.09350459, -0.46184233,  0.49074098]])

In [34]:
np.correlate([-1.33218407, -0.14747529, -0.75239626, -0.32468267],[ 2.54807613,  0.83777292, -1.34330607, -0.04318903],'same')
# Correlação cruzada de duas sequências 1-dimensional.

array([ 1.79590026, -0.88546802, -2.49333604, -0.56996728])

In [35]:
np.correlate([-1.33218407, -0.14747529, -0.75239626, -0.32468267],[ 2.54807613,  0.83777292, -1.34330607, -0.04318903],'full')

array([ 0.05753574,  1.79590026, -0.88546802, -2.49333604, -0.56996728,
       -2.1891733 , -0.82731616])

In [37]:
np.correlate([-1.33218407, -0.14747529, -0.75239626, -0.32468267],[ 2.54807613,  0.83777292, -1.34330607],'full')

array([ 1.78953095, -0.91796329, -2.50735877, -0.56996728, -2.1891733 ,
       -0.82731616])

In [39]:
np.cov(arr) # Estime a matriz de covariância, tendo em conta dados e pesos.

array([[ 0.27791822, -0.40512661, -0.49481522,  0.13168935,  0.32529387],
       [-0.40512661,  2.66717929,  0.30796177, -1.63039631,  0.08995237],
       [-0.49481522,  0.30796177,  1.54264412,  0.65240091, -0.66296662],
       [ 0.13168935, -1.63039631,  0.65240091,  1.68126585, -0.20710209],
       [ 0.32529387,  0.08995237, -0.66296662, -0.20710209,  0.53540158]])