In [1]:
import numpy as np

In [2]:
arr = np.arange(0,30,3) # array vetor de 0 a 30 com intervalos de 3 em 3

In [3]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
arr[2] # exibe o segundo indice do objeto array arr

6

In [5]:
arr[4] # exibe o quarto indice do objeto array arr

12

In [6]:
arr[2:5] # exibe indice no intervalo do segundo elemnto ate o quinto elemento

array([ 6,  9, 12])

In [7]:
arr[3:] # exibe do terceiro elemnto adiante

array([ 9, 12, 15, 18, 21, 24, 27])

In [8]:
arr[:3] # exibe do terceiro indice ao primeiro indice do array

array([0, 3, 6])

In [9]:
arr[:5] = 100 # do quinto indice ao primeiro todos serão igual a 100

In [10]:
arr

array([100, 100, 100, 100, 100,  15,  18,  21,  24,  27])

### Array bidimensional

In [11]:
arr = np.arange(50).reshape((5,10)) # array de 50 elemntos e com a função reshape o torna um array de 10 x 5 de duas dimensoes

In [12]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
arr.shape # exibe as dimensoes do array 5 linhas por 10 colunas

(5, 10)

In [14]:
arr[:3] # extrai as tres linhas dentre as 5 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
arr[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [18]:
arr[3][4] # terceira coluna na quarta linha 

34

In [19]:
arr[3][7] # terceira coluna na setima linha

37

In [20]:
arr[3][7] = 50 # indice da terceira coluna na setima linha passa a ter valor 50

In [21]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 50, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [24]:
arr[:,2] # retorna a segunda coluna de arr

array([ 2, 12, 22, 32, 42])

In [25]:
arr[2,:] # retorna a segunda linha de arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
arr[:2,:3] # duas colunas da segunda adiante e tres linhas da terceira adiante

array([[ 0,  1,  2],
       [10, 11, 12]])

In [27]:
arr[:3,:2] # tres colunas da segunda adiante e duas linhas da terceira adiante

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [30]:
arr[4:,2:] #extrai todos os elemntos da segunda coluna e na quarta linha

array([[42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
arr[2,9]

29

In [35]:
arr[1:4,5:] # da quinta coluna adiante extrair todos os indices das linhas 1 a 4 

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 50, 38, 39]])

In [37]:
arr > 39 # quais valores dentro do array arr são maiores que 39

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [38]:
bol = arr > 30 # cria o objeto booleano bol

In [39]:
arr[bol] # extrai os valores maiores que 30 

array([31, 32, 33, 34, 35, 36, 50, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])