In [1]:
# importar numpy
# referenciar numpy em np, importando numpy para ser usado como np
import numpy as np

In [3]:
minha_lista = [1,2,3] # definindo minha_lista com lista contendo tres elementos

In [4]:
minha_lista # exibindo minha lista

[1, 2, 3]

In [5]:
type(minha_lista) # minha_lista do tipo list

list

In [6]:
np.array(minha_lista) # converte minha_lista em um array de python, lista de uma dimensão

array([1, 2, 3])

In [7]:
type(minha_lista) # minha_lista como sendo objeto do tipo lista

list

In [8]:
minha_lista_array = np.array(minha_lista) # atribuindo o array numpy ao objeto minha_lista_array

In [9]:
type(minha_lista_array) # exibindo o tipo do objeto minha_lista_array

numpy.ndarray

In [10]:
minha_lista_array # lista de uma dimensão

array([1, 2, 3])

In [11]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]] # lista que sera convertida em matriz de duas dimensões

In [14]:
minha_matriz # exibindo como lista
type(minha_matriz)

list

In [13]:
np.array(minha_matriz) # convertendo em matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
minha_matriz_np = np.array(minha_matriz)

In [16]:
type(minha_matriz_np)

numpy.ndarray

#### OBS: O tamanho da matriz e referenciado pela quantidade de colchetes, no caso dois

In [17]:
minha_matriz_tres_dimensoes = [[[1,2,3],[4,5,6],[7,8,9]]]

In [18]:
minha_matriz_tres_dimensoes

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [19]:
np.array(minha_matriz_tres_dimensoes) # tres colchetes, matriz de 3 dimensoes

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
x = [[[[1,2,3],[4,5,6],[7,8,9]]]]

In [25]:
x

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]]

In [26]:
np.array(x) # matriz de 4 dimensoes

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [27]:
np.arange(0,10) # cria um objeto array de 10 elementos 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,20,2) # cria um objeto array de 0 a 20 contando de 2 a 2 (intervalo)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##### Shift + Tab exibe a documentação do metodo 

#### np.arange(inicio, fim, intervalo)

In [30]:
np.arange(0,31,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [31]:
np.zeros(3) # metodo zeros, cria um array de 3 zeros

array([0., 0., 0.])

In [32]:
arr = np.zeros((5,5)) # matriz de zeros de duas dimensoes

In [33]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones((3,3)) # cria uma matriz de 3 x 3 de duas dimensoes preenchidas com numero um

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(4) # criando uma matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.linspace(0,10,3) # metodo linspace mostra quantos numeros serao visualizados no intervalo 
# np.linspace(inicio, fim,quantidade de numeros)

array([ 0.,  5., 10.])

In [46]:
np.linspace(0,30,5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [47]:
np.random.rand(5) # metodo rand do modulo random , cria numeros aleatorios de 0 a 1 distribuição uniforme

array([0.1316931 , 0.72509328, 0.42882232, 0.61853995, 0.91486535])

In [48]:
np.random.rand(7) * 100

array([44.22541977, 24.19861097, 73.55378394, 26.55388191, 12.06382256,
       17.54477358, 17.96413345])

In [50]:
np.random.rand(5,4) # matriz de 5 linhas por 4 colunas de duas dimensões

array([[0.60314998, 0.06839853, 0.40990803, 0.04317601],
       [0.53367821, 0.61032727, 0.22997894, 0.07802496],
       [0.64543915, 0.32005032, 0.49528898, 0.16831951],
       [0.91339395, 0.08967306, 0.688582  , 0.97638239],
       [0.30269521, 0.29660939, 0.22964758, 0.36824651]])

In [51]:
np.random.rand(5,5,5) # matriz de tres dimensoes

array([[[0.52475362, 0.02599819, 0.22614697, 0.62621151, 0.09511075],
        [0.72208606, 0.55687416, 0.71962878, 0.30233469, 0.04123413],
        [0.67019192, 0.57368277, 0.95953236, 0.87461454, 0.22099195],
        [0.80895294, 0.75764902, 0.99849957, 0.74830097, 0.8086035 ],
        [0.97620674, 0.74374135, 0.00289326, 0.25674479, 0.6777416 ]],

       [[0.33944898, 0.57636033, 0.12444936, 0.5707604 , 0.42265335],
        [0.44513315, 0.03374077, 0.84271272, 0.97950845, 0.11627323],
        [0.78436859, 0.87668223, 0.88895119, 0.32529206, 0.69011365],
        [0.24935325, 0.80387897, 0.10874801, 0.96595835, 0.51020663],
        [0.09428381, 0.42901049, 0.05227746, 0.90942025, 0.78997079]],

       [[0.78147682, 0.53229705, 0.59565209, 0.00626909, 0.00436823],
        [0.79719078, 0.13227372, 0.44576004, 0.28154634, 0.87183315],
        [0.56581293, 0.81110732, 0.03823848, 0.03817129, 0.82990858],
        [0.11141666, 0.35884748, 0.8815064 , 0.5459583 , 0.34390107],
        [0.21552

In [52]:
np.random.randn(4) # distribuição nao uniforme, distribuição Gaussiana

array([-1.93355054,  1.00288722,  0.65429244,  0.445868  ])

In [53]:
np.random.randint(0,10,5) # metodo randint cria numeros inteiros aleatorios baseados no numero de quantidades
# np.random.randint(inicio, fim,numero de quantidade)

array([8, 5, 1, 7, 7])

In [61]:
np.round(np.random.randn(4)*100, 0) # metodo round arredonda numeros 

array([  25.,   33., -151.,    6.])

In [62]:
np.round(np.random.rand(3,3,3)*100, 0)

array([[[96., 34., 54.],
        [15., 81.,  1.],
        [ 6., 47., 75.]],

       [[65., 11., 58.],
        [10., 37., 44.],
        [21., 70., 66.]],

       [[86., 88., 97.],
        [40., 47., 43.],
        [53., 18., 41.]]])

In [63]:
arr = np.random.rand(25) # vetor de 25 elementos

In [64]:
arr

array([0.60771601, 0.47814178, 0.67166489, 0.4910196 , 0.79543521,
       0.05078278, 0.17009924, 0.47499014, 0.43564689, 0.06794964,
       0.09247902, 0.64708811, 0.42442446, 0.1944216 , 0.18157131,
       0.678754  , 0.09334119, 0.0613804 , 0.25618201, 0.00184049,
       0.74413192, 0.47108197, 0.5001186 , 0.29518768, 0.61128471])

In [65]:
arr.reshape((5,5)) # recria a matriz no objetos arr para uma matriz de 5 X 5 com dus dimensoes

array([[0.60771601, 0.47814178, 0.67166489, 0.4910196 , 0.79543521],
       [0.05078278, 0.17009924, 0.47499014, 0.43564689, 0.06794964],
       [0.09247902, 0.64708811, 0.42442446, 0.1944216 , 0.18157131],
       [0.678754  , 0.09334119, 0.0613804 , 0.25618201, 0.00184049],
       [0.74413192, 0.47108197, 0.5001186 , 0.29518768, 0.61128471]])

In [66]:
arr_new = arr.reshape((5,5))

In [67]:
arr_new

array([[0.60771601, 0.47814178, 0.67166489, 0.4910196 , 0.79543521],
       [0.05078278, 0.17009924, 0.47499014, 0.43564689, 0.06794964],
       [0.09247902, 0.64708811, 0.42442446, 0.1944216 , 0.18157131],
       [0.678754  , 0.09334119, 0.0613804 , 0.25618201, 0.00184049],
       [0.74413192, 0.47108197, 0.5001186 , 0.29518768, 0.61128471]])

In [70]:
arr.shape # parametro para mostrar o tipo do array
# vetor de 25 elementos

(25,)

In [71]:
arr_new.shape
# matriz de duas dimensoes de 5 colunas por 5 linhas

(5, 5)

In [72]:
arr.max() # metodo que encontra o maior valor dentro do array

0.7954352116597492

In [73]:
arr.min() # metodo que encontra o menor valor dentro do array

0.0018404890646902539

In [74]:
arr.mean() # metodo que encontra a media dos elemntos do array

0.379869346321332

In [75]:
arr_new.mean()

0.379869346321332

In [76]:
np.round(arr.mean()*100,0) 

38.0

In [77]:
np.round(arr.max()*100,0)

80.0

In [78]:
arr.argmax() # metodo que encontra o indice da posição do elemento na matriz , elemnto com valor maximo

4

In [79]:
arr.argmin() # metodo que encontra o indice da posição do elemento na matriz , elemnto com valor minimo

19

In [80]:
arr_new.argmax()

4

In [ ]:
arr_new.argmin