In [1]:
from IPython.core.display import HTML
HTML('''
<style>
h1,h2,h3,h4,h5,h6,p,p.h1,p.h2.p.h3,p.h4,p.h5,p.h6{
color:#772953;
}
.fab,.fas {
    margin-right: 10px;
}
kbd {
    background-color: #772953;
    color: white;
</style>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<script>
var logoParent = document.getElementById("kernel_logo_widget")
var logo = document.getElementById("kernel_logo_widget").getElementsByClassName("current_kernel_logo")[0];
logo.src = "https://raw.githubusercontent.com/Janderscience/DataScience/master/logo.png";
logo.style = "display: inline; width:170px; height:34px";
logoParent.innerHTML = '<a href="https://github.com/Janderscience/DataScience">' + logoParent.innerHTML + '</a>';
</script>
''')

In [1]:
import numpy as np

In [2]:
# numpy array podem ser de duas formas: vetores e matrizes
# vetores são arrays, matrizes sao 2-D, e podem cconter apenas umma linha ou coluna

In [3]:
minha_lista = [1,2,3]

In [4]:
# criando um array com a lista
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# matriz de duas dimensoes, as dimensoes são vistas 
# pela quantidade de colchetes
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# cria uma sequencia numerica de inicio e fim
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# cria uma sequencia numerica de incio e fim com uso de step
# no caso contando numeros pares
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
# array de numeros impares
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
# matriz de elemmnto zerados
np.zeros(3)

array([0., 0., 0.])

In [15]:
# matriz de uns 
np.ones(3)

array([1., 1., 1.])

In [16]:
# matriz de zeros , e de duas dimensoes (5,5)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# matriz identidade
# tem uns em sua diagonal e o restante zero
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# numeros igualmente espaçados
np.linspace(0,10,2)

array([ 0., 10.])

In [19]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [20]:
# radomizando numeros
np.random.rand(5)

array([0.73619502, 0.56291095, 0.46412107, 0.31444238, 0.15075121])

In [21]:
# pegando numeros de o a 100
np.random.rand(5) * 100

array([59.40889923, 33.40815772, 50.05308755, 40.98982413, 75.50735537])

In [22]:
np.random.rand(5,4) * 100

array([[46.49462471, 53.95435658, 13.00926244, 32.90408967],
       [14.89872517,  3.79102236, 50.81145498, 41.86765207],
       [66.82379701,  8.59250735, 70.1586991 , 42.82450342],
       [50.20941969, 55.54228376, 24.4154711 , 62.03932116],
       [ 7.94947459, 40.50153244, 16.15920272, 95.14867998]])

In [23]:
# matriz de 3 dimensoes
np.random.rand(5,4, 3) * 100

array([[[12.24608733, 48.9209655 , 70.4745671 ],
        [54.57691152, 48.36430499, 78.0276268 ],
        [23.25692893, 32.29572555, 15.94628146],
        [56.38211833,  0.27384009, 58.16598587]],

       [[38.45284474,  0.2461297 , 52.78553691],
        [98.78095337, 46.78640447, 47.18189382],
        [72.78287109, 62.83542513, 63.5145202 ],
        [34.86079266, 28.61513998, 13.53086679]],

       [[88.70261267, 88.98355569, 27.96369086],
        [50.9900564 , 87.49519845, 31.26926039],
        [27.15996704, 94.21318825, 78.28249504],
        [98.13555454, 46.48757855, 50.63270331]],

       [[41.42101056, 86.73893911,  0.09964853],
        [95.81801538, 28.55179598, 70.32755467],
        [22.45263513,  2.62382015, 80.54206479],
        [88.30036925,  3.44286242,  8.90898159]],

       [[15.08256611,  3.90960329, 87.31861228],
        [68.76475088, 90.07693385, 25.54054475],
        [54.94603958, 20.37706945, 72.22463212],
        [67.62222351, 54.26938398, 79.91693275]]])

In [25]:
# distribuição normal, uniforme, numeros aleatorios
np.random.rand(5)

array([0.32294624, 0.45997559, 0.42424179, 0.97203971, 0.68787367])

In [26]:
# distribuição gausiana 
np.random.randn(5)

array([-1.13124005, -1.41658575,  0.09695087,  0.55764843,  1.16706184])

In [28]:
# numeros aleatorios com intervalos de inicio e fim
np.random.randint(0,100,10)

array([71, 89, 12, 35, 61, 15,  7, 50, 87, 11])

In [29]:
# arredondando valores
np.round(np.random.rand(5)*100, 0)

array([82.,  6., 51., 21., 89.])

In [30]:
# criando um vetos de tamanho 25
arr = np.random.rand(25)

In [31]:
arr

array([0.32666582, 0.94054357, 0.72831796, 0.56063064, 0.42942563,
       0.58574229, 0.51987329, 0.5337763 , 0.12550025, 0.21251101,
       0.57455504, 0.59324859, 0.34315117, 0.69931196, 0.43344309,
       0.41367817, 0.08360741, 0.72821076, 0.86264238, 0.38405788,
       0.68114943, 0.36374967, 0.37700462, 0.01982583, 0.59941984])

In [38]:
# tornamdo o vetor uma matriz de 5 x 5
arr.reshape((5,5))

array([[0.32666582, 0.94054357, 0.72831796, 0.56063064, 0.42942563],
       [0.58574229, 0.51987329, 0.5337763 , 0.12550025, 0.21251101],
       [0.57455504, 0.59324859, 0.34315117, 0.69931196, 0.43344309],
       [0.41367817, 0.08360741, 0.72821076, 0.86264238, 0.38405788],
       [0.68114943, 0.36374967, 0.37700462, 0.01982583, 0.59941984]])

In [41]:
arr = arr.reshape((5,5))
arr.shape

(5, 5)

In [42]:
# encontrando maior valor
arr.max()

0.9405435723179119

In [43]:
# encontrando menor valor
arr.min()

0.01982582892130702

In [44]:
# retorna o indice ao qual o maior elemnto se encontra
arr.argmax()

1

In [46]:
# retorna o indce onde o menor elemnto se encontra
arr.argmin()

23

## Indexação e fatiamento

In [63]:
arr = np.arange(0,30,3)

In [64]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [65]:
# retornando o indice
arr[3]

9

In [66]:
# retornando o indice
arr[6]

18

In [67]:
# retornando o indice
arr[-4]

18

In [68]:
# da posição 2 a posição 4
arr[2:5]

array([ 6,  9, 12])

In [69]:
# busca todos os elemntos ate o indice 5
arr[:5]

array([ 0,  3,  6,  9, 12])

In [70]:
# inclui o indice 2 adiante
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [71]:
# a partir do indice 2 todos os elemntos valem 100
arr[2:] = 100

In [72]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr = np.arange(50).reshape((5,10))

In [74]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
arr.shape

(5, 10)

In [76]:
# fatiamento ou slices 
# pode usar um colchete ou dois colchetes
# primeiro colchete faz menção as linhas e o segundo as colunas
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [82]:
arr[:][:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [86]:
arr2 = arr[:3].copy()

In [87]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [88]:
arr.shape

(5, 10)

In [89]:
arr[:4][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [92]:
arr[:4,8:]

array([[ 8,  9],
       [18, 19],
       [28, 29],
       [38, 39]])

In [94]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [96]:
arr[1:3,6:8]

array([[16, 17],
       [26, 27]])

In [97]:
# analisa no array todos os valores maiores que 50 e retorna True ou False
arr > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [100]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [101]:
bol = arr > 50

In [104]:
arr[bol]

array([], dtype=int64)

## Operações com arrays

In [105]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [106]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [107]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [108]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [110]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [111]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [112]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [113]:
arr.sum()

120

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [115]:
(arr / 120) * 100

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        , 10.83333333, 11.66666667,
       12.5       ])

In [116]:
arr.shape

(16,)

In [121]:
# raiz quadrada
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [122]:
# exponenciação
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [123]:
# media
np.mean(arr)

7.5

In [124]:
# desvio padrao
np.std(arr)

4.6097722286464435

In [125]:
# seno
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [126]:
np.max(arr)

15

In [127]:
np.min(arr)

0