In [5]:
from IPython.core.display import HTML
HTML('''
<style>
h1,h2,h3,h4,h5,h6,p,p.h1,p.h2.p.h3,p.h4,p.h5,p.h6{
color:#772953;
}
.fab,.fas {
    margin-right: 10px;
}
kbd {
    background-color: #772953;
    color: white;
</style>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<script>
var logoParent = document.getElementById("kernel_logo_widget")
var logo = document.getElementById("kernel_logo_widget").getElementsByClassName("current_kernel_logo")[0];
logo.src = "logo.png";
logo.style = "display: inline; width:170px; height:34px";
logoParent.innerHTML = '<a href="https://github.com/Janderscience/DataScience">' + logoParent.innerHTML + '</a>';
</script>
''')

<h2><i class="fas fa-award"></i>NIVEL FÀCIL</h2>

<h3><i class="fas fa-chevron-circle-right"></i>1- Importe numpy como ‘np’ e imprima o número da versão.</h3>

In [9]:
import numpy as np
print(np.__version__)

1.15.4


<h3><i class="fas fa-chevron-circle-right"></i>2- Crie uma matriz 1D com números de 0 a 9</h3>

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3><i class="fas fa-chevron-circle-right"></i>3- Crie uma matriz booleana numpy 3×3 com ‘True’</h3>

In [17]:
arr = np.array([[3,3,3],[3,3,3],[3,3,3]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr == 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

<h3><i class="fas fa-chevron-circle-right"></i>4- Extraia todos os números ímpares de ‘arr’</h3>

In [54]:
x = np.arange(0,10)
arr = (x[x%2!=0])
arr

array([1, 3, 5, 7, 9])

<h3><i class="fas fa-chevron-circle-right"></i>5- Substitua todos os números ímpares arr por -1</h3>

In [55]:
x = np.arange(0,10)
np.place(x, x % 2 != 0, -1)
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

<h2><i class="fas fa-award"></i><i class="fas fa-award"></i>NIVEL MÈDIO</h2>

<h3><i class="fas fa-chevron-circle-right"></i>1- Substitua todos os números ímpares em arr com -1 sem alterar arr</h3>

In [62]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array = np.arange(0,10)
np.place(array, array % 2 != 0, -1)
print(array)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


<h3><i class="fas fa-chevron-circle-right"></i>2-Converta uma matriz 1D para uma matriz 2D com 2 linhas:</h3>

In [65]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

 <h3><i class="fas fa-chevron-circle-right"></i>3 - Empilhe matrizes verticalmente:</h3>

In [69]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b),axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<h3><i class="fas fa-chevron-circle-right"></i>4- Empilhe as matrizes horizontalmente:</h3>

In [68]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

<h3><i class="fas fa-chevron-circle-right"></i>5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.</h3>

In [80]:
a = np.array([1,2,3])
x = np.repeat(a,3)
y = np.tile(a,3)
np.concatenate((x,y))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

<h2><i class="fas fa-award"></i><i class="fas fa-award"></i><i class="fas fa-award"></i>NIVEL DIFÌCIL</h2>

<h3><i class="fas fa-chevron-circle-right"></i>1- Calcule a pontuação softmax de ‘sepal length’:</h3>

In [85]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
sepallength = np.genfromtxt(url, delimiter=",", dtype="float", usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [87]:
def softmax(sepallength):
    e_sepallength = np.exp(sepallength - np.max(sepallength))
    return e_sepallength / e_sepallength.sum()
scores = [3.0, 1.0, 0.2]
print(softmax(scores))

[0.8360188  0.11314284 0.05083836]


<h3><i class="fas fa-chevron-circle-right"></i>2- Filtre as linhas de iris_2d que possuem petallength (coluna 3) > 1.5 e sepallength (coluna 1) < 5.0</h3>

In [89]:
iris_2d = np.genfromtxt(url, delimiter=",", dtype="float", usecols=[0,1,2,3])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [90]:
iris_2d.shape

(150, 4)

<h3><i class="fas fa-chevron-circle-right"></i>3- Selecione as linhas de iris_2d que não têm nenhum valor ‘nan’</h3>

In [123]:
iris_2d = np.genfromtxt(url, delimiter=",", dtype="float", usecols=[0,1,2,3])

<h3><i class="fas fa-chevron-circle-right"></i>4- Calcule as contagens de valores únicos na linha.</h3>

<h3><i class="fas fa-chevron-circle-right"></i>5- Encontre todos os picos em uma matriz 1D numpy ‘a’. Picos são pontos cercados por valores menores em ambos os lados.</h3>

In [124]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

<h3><i class="fas fa-chevron-circle-right"></i>6- Calcule as codificações únicas (variáveis ​​binárias dummy para cada valor único na matriz)</h3>

In [125]:
np.random.seed(101)
arr = np.random.randint(1,4, size=6)
print(arr)

[2 3 2 2 2 1]
