1- Importe numpy como ‘np’ e imprima o número da versão.

In [1]:
import numpy as np

2- Crie uma matriz 1D com números de 0 a 9

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [17]:
arr = np.array([[3,3,3],[3,3,3],[3,3,3]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr == 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4- Extraia todos os números ímpares de ‘arr’

In [54]:
x = np.arange(0,10)
arr = (x[x%2!=0])
arr

array([1, 3, 5, 7, 9])

5- Substitua todos os números ímpares arr por -1

In [55]:
x = np.arange(0,10)
np.place(x, x % 2 != 0, -1)
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [62]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array = np.arange(0,10)
np.place(array, array % 2 != 0, -1)
print(array)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


2-Converta uma matriz 1D para uma matriz 2D com 2 linhas:

In [65]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])