In [3]:
import numpy as np
import matplotlib.pyplot as plt

### matriz identidade

#### matriz quadrada: mesmo numero de linhas e colunas

#### matriz identidade: matriz quadrada ,onde todos os elemntos na diagonal são igual a 1 e demais elementos igual a zero

In [5]:
d = np.eye(2) # matriz identidade 2x2

In [6]:
d

array([[1., 0.],
       [0., 1.]])

In [7]:
arr = np.eye(10)

In [8]:
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
a = np.array([[1,2],[3,4],[5,6]])

In [10]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a[a>3] # imprimir somente os elemntos do array maiores que 3

array([4, 5, 6])

In [13]:
a[a<3] # imprimir somente os elemntos do array menores que 3

array([1, 2])

In [14]:
a[a>1] # imprimir somente os elemntos do array maiores que 1

array([2, 3, 4, 5, 6])

In [17]:
bol = [a>2] # somente valores maiores que 2

In [18]:
bol

[array([[False, False],
        [ True,  True],
        [ True,  True]])]

In [20]:
val1,val2,val3 = np.loadtxt('dados.txt',skiprows=1,unpack=True) 
# cria tres variaveis para cada campo do arquivo dados.txt
# skiprows, exclui a linha 1 do arquivo, 2 exclui a segunda linha
# np.loadtxt carrega o arquivo txt no mesmo diretorio 
# unpack=True coloca cada coluna do arquivo dados.txt em sua respectiva coluna variavl valx

In [21]:
# imprimindo as variaveis
print(val1)
print(val2)
print(val3)

[0.1212 0.104  0.5661 0.762 ]
[0.842    0.5422   0.932    0.847361]
[0.3672  0.34551 0.2344  0.1538 ]


In [23]:
type(val1)

numpy.ndarray

#### Dataset com dados faltantes e queremos preencher, por exemplo, com 100

In [24]:
my_array = np.genfromtxt('dados2.txt',skip_header=1,filling_values=100)
# np.genfromtxt carrega o arquivo
# skip_header=1 exlui a linha 1 ou seja o cabeçalho 
# filling_values=100 valores faltantes serão preenchidos com 100

In [25]:
my_array # posição 3 e 8 sera preenchida com 100, pois esta ausente no dataset

array([[  0.1212  ,   0.842   ,   0.3672  ],
       [100.      ,   0.5422  ,   0.34551 ],
       [  0.5661  ,   0.932   , 100.      ],
       [  0.762   ,   0.847361,   0.1538  ]])

#### preencher os valores faltantes com a media dos dados

In [26]:
np.sum(my_array) # encontrado a soma total

205.479371

In [27]:
np.mean(my_array) # a media e 17

17.123280916666666

In [29]:
np.round(np.mean(my_array),0) # arrendondado a media 

17.0

In [30]:
media = np.round(np.mean(my_array),0)

In [31]:
media

17.0

In [32]:
my_array_media = np.genfromtxt('dados2.txt',skip_header=1,filling_values=media) # usar a variavel media em filling_values

In [33]:
my_array_media

array([[ 0.1212  ,  0.842   ,  0.3672  ],
       [17.      ,  0.5422  ,  0.34551 ],
       [ 0.5661  ,  0.932   , 17.      ],
       [ 0.762   ,  0.847361,  0.1538  ]])

In [34]:
np.round(np.sum(my_array_media))

39.0

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
b

array([[5, 6]])

In [44]:
np.concatenate((a,b),axis=0)
# metodo np.concatenate concatena arrays
# concatena arrays no eixo 0 (linha)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np.concatenate((a,b.T),axis=1) # no axis=1 teremos de fazer a matriz transposta de b, pois b e uma linha, nao uma coluna

array([[1, 2, 5],
       [3, 4, 6]])

In [47]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [48]:
x.shape

(2, 2)

In [49]:
y.shape

(2, 2)

In [51]:
x.ndim

2

In [52]:
y.ndim

2

In [53]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [55]:
z = np.concatenate((x,y), axis=1)

In [56]:
z

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [59]:
sum(z[:,1])

6

In [60]:
sum(z[:,2])

12

In [61]:
sum(z[0,:])

14

In [62]:
sum(z[1,:])

22

In [63]:
a = np.arange(10)

In [64]:
a # array ordenado em ordem crescente

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.random.shuffle(a) # metodo shuffle do pacote random embaralha a sequencia do array a

In [66]:
a

array([0, 4, 9, 5, 1, 8, 6, 7, 3, 2])

In [67]:
a

array([0, 4, 9, 5, 1, 8, 6, 7, 3, 2])

In [68]:
a.sum()

45

In [69]:
a = np.array([1,10+2j,20+5j],dtype=complex) # numeros complexos

In [70]:
a

array([ 1.+0.j, 10.+2.j, 20.+5.j])

In [71]:
a[1]

(10+2j)

In [72]:
a[2]

(20+5j)

In [73]:
a[0]

(1+0j)

In [74]:
a[1]+a[2]

(30+7j)

In [75]:
a[1] - a[2]

(-10-3j)

In [76]:
a[1] * a[2]

(190+90j)

In [77]:
a[1]

(10+2j)

In [78]:
a[2]

(20+5j)

In [79]:
np.linspace(2.0,3.0,5) # metodo gera numeros uniformemente espaçados

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [81]:
np.linspace(1.0,6.0) # gera numeros uniformente espaçados , como nao passou a quantidade, ele gera automaticamente 50 numeros

array([1.        , 1.10204082, 1.20408163, 1.30612245, 1.40816327,
       1.51020408, 1.6122449 , 1.71428571, 1.81632653, 1.91836735,
       2.02040816, 2.12244898, 2.2244898 , 2.32653061, 2.42857143,
       2.53061224, 2.63265306, 2.73469388, 2.83673469, 2.93877551,
       3.04081633, 3.14285714, 3.24489796, 3.34693878, 3.44897959,
       3.55102041, 3.65306122, 3.75510204, 3.85714286, 3.95918367,
       4.06122449, 4.16326531, 4.26530612, 4.36734694, 4.46938776,
       4.57142857, 4.67346939, 4.7755102 , 4.87755102, 4.97959184,
       5.08163265, 5.18367347, 5.28571429, 5.3877551 , 5.48979592,
       5.59183673, 5.69387755, 5.79591837, 5.89795918, 6.        ])

In [82]:
a = np.array([[1,2],[2,3],[3,3],[4,4]])

In [83]:
a

array([[1, 2],
       [2, 3],
       [3, 3],
       [4, 4]])

In [84]:
np.unique(a) # exibir elementos unicos que não se repetem

array([1, 2, 3, 4])

In [85]:
len(np.unique(a))

4

In [89]:
valores = np.genfromtxt("arquivo.csv", delimiter=",",skip_header=1)

In [90]:
valores

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.],
       [34., 54., 23.]])